### PR TITLE
evm: Explicitly check staticcalls

### PR DESCRIPTION
**Pull request by djb15**

### CODE REVIEW

**Comment by mdulin2** [comment]
Can you check the result on this one as well - https://github.com/wormhole-foundation/example-native-token-transfers/blob/fb39daa2a6b6f5bc9289c0bc48f376880e26853c/evm/test/libraries/NttManagerHelpers.sol#L20

**Review by mdulin2 — DISMISSED** [review]
Add the check in the other location and I think it's good to go.

**Review by RahulMaganti47 — DISMISSED** [review]
can you add a negative test for this? otherwise, lgtm

**Comment by RahulMaganti47** [comment]
> Can you check the result on this one as well -
> 
> https://github.com/wormhole-foundation/example-native-token-transfers/blob/fb39daa2a6b6f5bc9289c0bc48f376880e26853c/evm/test/libraries/NttManagerHelpers.sol#L20

might be nice to add but probably not necessary since this is in the tests (unless that error is being tested specifically)?

**Review by RahulMaganti47 — APPROVED** [review]

**Comment by mdulin2** [comment]
> > Can you check the result on this one as well -
> > https://github.com/wormhole-foundation/example-native-token-transfers/blob/fb39daa2a6b6f5bc9289c0bc48f376880e26853c/evm/test/libraries/NttManagerHelpers.sol#L20
> 
> might be nice to add but probably not necessary since this is in the tests (unless that error is being tested specifically)?

Ahh, you're right. I didn't see this was in the tests - I just saw library and figured it was under the hood.

**Review by mdulin2 — APPROVED** [review]

**Pull request merged**
